@host = http://localhost:56598

###
GET {{host}}/api/todo-items
Accept: application/json

###
GET {{host}}/api/todo-items/0
Accept: application/json

###
POST {{host}}/api/todo-items
Content-Type: application/json

"Watch TV"

###
PUT {{host}}/api/todo-items/2
Content-Type: application/json

"Watch Netflix"

###
DELETE {{host}}/api/todo-items/2

###
GET {{host}}/api/todo-items/sorted?sortOrder=asc
Accept: application/json

###
# ==============================================================================
GET {{host}}/api/todo-items-advanced
Accept: application/json

###
GET {{host}}/api/todo-items-advanced/0
Accept: application/json

###
POST {{host}}/api/todo-items-advanced
Content-Type: application/json

{
    "description": "Watch TV",
    "assignedTo": "Me"
}

###
POST {{host}}/api/todo-items-advanced
Content-Type: application/json

{
    "description": "x",
    "assignedTo": "Me"
}

###
PUT {{host}}/api/todo-items-advanced/2
Content-Type: application/json

{
    "description": "Watch Netfix",
    "assignedTo": "Me"
}

###
DELETE {{host}}/api/todo-items-advanced/2

